In [1]:
%load_ext autoreload
%autoreload 2

import sys
import featuregraph as fg

from featuregraph.accumulation.accumulations import add_accumulation_signal, add_accumulation_id, add_accumulation_primitives, add_accumulation_features, get_accumulation_summary

print("Python:", sys.executable)
print("FeatureGraph:", fg.__file__)

Python: /usr/local/bin/python
FeatureGraph: /workspaces/featuregraph/src/featuregraph/__init__.py

In [2]:
bidmc = fg.datasets.bidmc(
    subject=1,
)

In [3]:
bidmc = fg.oscillation.waves.add_wave_primitives(bidmc, ['respiration'])
bidmc = fg.oscillation.waves.add_wave_id(bidmc, ['respiration'], 'subject')
bidmc = fg.oscillation.waves.add_wave_features(bidmc, ['respiration'], 'respiration_wave_id')
bidmc

,time,respiration,ppg,ecg_v,ecg_avr,ecg_ii,subject,respiration_rising,respiration_falling,enter_respiration_rising,exit_respiration_rising,respiration_peak_index,respiration_trough_index,respiration_wave_id,respiration_rising_time,respiration_falling_time,respiration_amplitude,respiration_duration
0,0.000,0.35386,0.43597,0.52549,0.30392,0.72549,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
1,0.008,0.35679,0.43206,0.51961,0.33529,0.67059,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
2,0.016,0.35875,0.42815,0.51569,0.37451,0.60980,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
3,0.024,0.36168,0.42424,0.50588,0.41961,0.55098,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
4,0.032,0.36364,0.42131,0.50980,0.44902,0.50000,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59996,479.970,0.15640,0.40567,0.50000,0.51961,0.40000,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
59997,479.980,0.15152,0.40371,0.50588,0.52941,0.39412,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
59998,479.980,0.14663,0.40176,0.50000,0.53529,0.38431,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
59999,479.990,0.14174,0.40176,0.50000,0.53922,0.38039,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
60000,480.000,0.13783,0.40274,0.49412,0.53529,0.38039,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37

In [4]:
bidmc = add_accumulation_signal(
    bidmc,
    signals=["respiration"],
    thresholds={'respiration': 'group_mean'},
    group='respiration_wave_id'
)

bidmc = add_accumulation_id(
    bidmc,
    signals=["respiration"],
)

bidmc = add_accumulation_primitives(
    bidmc,
    signals=["respiration"],
)

bidmc = add_accumulation_features(
    bidmc,
    signals=["respiration"],
)

summarydf = get_accumulation_summary(
    bidmc,
    signal="respiration",
)

In [5]:
summarydf

,accumulation_id,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,0,0,9,10,0.353860,0.093840,0.000000,0.093840,0.000000,0.009384,0.000000,5.989344,6
1,1,0,69,70,0.018573,9.866038,1.737045,1.393938,8.472100,0.140943,0.282573,18.677637,15
2,2,0,210,211,0.030303,121.809414,45.742933,44.773236,77.036178,0.577296,0.735136,105.345667,103
3,3,0,73,74,0.019550,9.390079,2.138800,1.906150,7.483929,0.126893,0.405992,24.088458,21
4,4,0,186,187,0.037146,107.700804,49.525838,48.562984,59.137820,0.575940,0.901813,96.828786,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550,550,0,94,95,0.096774,11.942353,8.267878,8.030342,3.912011,0.125709,0.655149,32.519312,33
551,551,0,56,57,0.098729,3.753673,2.547406,2.442815,1.310858,0.065854,0.698440,33.322150,33
552,552,0,201,202,0.169110,98.348120,54.841690,54.010800,44.337320,0.486872,0.901640,107.061031,110
553,553,0,84,85,0.126100,11.359690,6.927640,6.677400,4.682290,0.133643,0.824369,26.060680,25
554,554,0,36,37,0.133920,1.027380,0.830900,0.790820,0.236560,0.027767,0.460511,19.904719,20