In [1]:
%load_ext autoreload
%autoreload 2

import sys
import featuregraph as fg

print("Python:", sys.executable)
print("FeatureGraph:", fg.__file__)

Python: /usr/local/bin/python
FeatureGraph: /workspaces/featuregraph/src/featuregraph/__init__.py

In [2]:
eastman = fg.datasets.eastman(
    fault_number=1,
    simulation_run=1,
)

bidmc = fg.datasets.bidmc(
    subject=1,
)

eastman_objects = fg.oscillate(
    eastman,
    signal="reactor_pressure",
    group=["fault_number", "simulation_run"],
    smooth=True,
)

bidmc_objects = fg.oscillate(
    bidmc,
    signal="respiration",
    group=["subject"],
)

In [4]:
eastman_objects

,oscillation_id,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,temporal_symmetry
0,0,NaN,NaN,NaN,0,0,0,NaN,0.155216,NaN
1,1,29.0,31.0,43.0,2,12,14,NaN,0.132400,0.285714
2,2,43.0,44.0,45.0,1,1,2,13.0,0.015504,1.000000
3,3,45.0,76.0,105.0,31,29,60,32.0,1.397994,0.966667
4,4,105.0,116.0,117.0,11,1,12,40.0,0.063443,0.166667
5,5,117.0,148.0,165.0,31,17,48,32.0,0.551637,0.708333
6,6,165.0,205.0,208.0,40,3,43,57.0,0.406232,0.139535
7,7,208.0,235.0,276.0,27,41,68,30.0,1.060868,0.794118
8,8,276.0,306.0,347.0,30,41,71,71.0,1.332329,0.845070
9,9,347.0,382.0,421.0,35,39,74,76.0,1.085307,0.945946
10,10,421.0,429.0,449.0,8,20,28,47.0,0.510682,0.571429
11,11,449.0,470.0,492.0,21,22,43,41.0,0.371507,0.976744
12,12,492.0,495.0,499.0,3,4,7,25.0,0.135117,0.857143
13,13,499.0,536.0,578.0,37,42,79,41.0,1.069514,0.936709
14,14,578.0,587.0,610.0,9,23,32,51.0,0.274522,0.562500
15,15,610.0,659.0,795.0,49,136,185,72.0,11.860252,0.529730
16,16,795.0,826.0,924.0,31,98,129,167.0,14.356878,0.480620
17,17,924.0,1054.0,1123.0,130,69,199,228.0,23.782994,0.693467
18,18,1123.0,1206.0,1288.0,83,82,165,152.0,2.319355,0.993939
19,19,1288.0,1317.0,1348.0,29,31,60,111.0,0.990875,0.966667
20,20,1348.0,1353.0,1385.0,5,32,37,36.0,0.766325,0.270270
21,21,1385.0,1410.0,1431.0,25,21,46,57.0,0.706629,0.913043
22,22,1431.0,1453.0,1462.0,22,9,31,43.0,0.507472,0.580645
23,23,1462.0,1511.0,1550.0,49,39,88,58.0,1.489048,0.886364
24,24,1550.0,1588.0,1599.0,38,11,49,77.0,1.262442,0.448980
25,25,1599.0,1604.0,1615.0,5,11,16,16.0,0.154558,0.625000
26,26,1615.0,1639.0,1660.0,24,21,45,35.0,0.653126,0.933333
27,27,1660.0,1680.0,1709.0,20,29,49,41.0,0.952367,0.816327
28,28,1709.0,1733.0,1765.0,24,32,56,53.0,0.890048,0.857143
29,29,1765.0,1818.0,1843.0,53,25,78,85.0,1.313833,0.641026
30,30,1843.0,1869.0,1873.0,26,4,30,51.0,0.329886,0.266667
31,31,1873.0,1876.0,1880.0,3,4,7,7.0,0.037297,0.857143
32,32,1880.0,1902.0,1921.0,22,19,41,26.0,0.412278,0.926829
33,33,1921.0,1932.0,1956.0,11,24,35,30.0,0.736700,0.628571
34,34,1956.0,1977.0,2006.0,21,29,50,45.0,0.663309,0.840000
35,35,2006.0,2048.0,2049.0,42,1,43,71.0,1.227782,0.046512
36,36,2049.0,2053.0,2100.0,4,47,51,5.0,1.316973,0.156863
37,37,2100.0,2123.0,2149.0,23,26,49,70.0,0.668473,0.938776
38,38,2149.0,2175.0,2196.0,26,21,47,52.0,0.783883,0.893617
39,39,2196.0,2222.0,2246.0,26,24,50,47.0,0.470284,0.960000
40,40,2246.0,2274.0,2296.0,28,22,50,52.0,0.453980,0.880000
41,41,2296.0,2301.0,2327.0,5,26,31,27.0,0.639598,0.322581
42,42,2327.0,2363.0,2386.0,36,23,59,62.0,0.890591,0.779661
43,43,2386.0,2436.0,2502.0,50,66,116,73.0,2.234683,0.862069
44,44,2502.0,2529.0,2545.0,27,16,43,93.0,0.567099,0.744186
45,45,2545.0,2564.0,2565.0,19,1,20,35.0,0.202176,0.100000
46,46,2565.0,2608.0,2633.0,43,25,68,44.0,0.854142,0.735294
47,47,2633.0,2651.0,2674.0,18,23,41,43.0,1.058520,0.878049
48,48,2674.0,2693.0,2704.0,19,11,30,42.0,0.413217,0.733333
49,49,2704.0,2737.0,2744.0,33,7,40,44.0,0.358539,0.350000
50,50,2744.0,2746.0,2782.0,2,36,38,9.0,0.836181,0.105263
51,51,2782.0,2816.0,2846.0,34,30,64,70.0,1.423312,0.937500
52,52,2846.0,2861.0,2862.0,15,1,16,45.0,0.154261,0.125000
53,53,2862.0,2863.0,2885.0,1,22,23,2.0,0.690043,0.086957
54,54,2885.0,2911.0,2923.0,26,12,38,48.0,0.950584,0.631579
55,55,2923.0,2926.0,2964.0,3,38,41,15.0,0.486503,0.146341
56,56,2964.0,2972.0,2975.0,8,3,11,46.0,0.055311,0.545455
57,57,2946.0,2972.0,2972.0,26,0,26,0.0,0.204870,0.000000

In [5]:
bidmc_objects

,oscillation_id,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,temporal_symmetry
0,0,NaN,NaN,NaN,0,0,0,NaN,0.007330,NaN
1,1,10.0,14.0,80.0,4,66,70,NaN,0.174974,0.114286
2,2,80.0,167.0,254.0,87,87,174,153.0,0.484849,1.000000
3,3,291.0,299.0,365.0,8,66,74,132.0,0.120235,0.216216
4,4,365.0,457.0,519.0,92,62,154,158.0,0.481427,0.805195
...,...,...,...,...,...,...,...,...,...,...
550,550,59525.0,59567.0,59619.0,42,52,94,108.0,0.122188,0.893617
551,551,59620.0,59659.0,59677.0,39,18,57,92.0,0.058160,0.631579
552,552,59677.0,59793.0,59846.0,116,53,169,134.0,0.415445,0.627219
553,553,59879.0,59908.0,59963.0,29,55,84,115.0,0.131475,0.690476
554,554,59964.0,59991.0,60001.0,27,10,37,83.0,0.022970,0.540541