In [23]:
%load_ext autoreload
%autoreload 2

import sys
import featuregraph as fg

print("Python:", sys.executable)
print("FeatureGraph:", fg.__file__)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Python: /usr/local/bin/python
FeatureGraph: /workspaces/featuregraph/src/featuregraph/__init__.py

In [24]:
eastman = fg.datasets.eastman(
    fault_number=1,
    simulation_run=1,
)

bidmc = fg.datasets.bidmc(
    subject=1,
)


eastman_oscillation = fg.oscillation.Oscillation(
    signals="reactor_temperature",
    group=["fault_number", "simulation_run"],
    smooth_signal=True,
    smooth_window=20,
)

eastman_features = eastman_oscillation.fit_transform(
    eastman
)

eastman_objects = eastman_oscillation.summarize(
    eastman_features,
    signal="reactor_temperature",
)


bidmc_oscillation = fg.oscillation.Oscillation(
    signals="respiration",
    group="subject",
    smooth_signal=False,
)

bidmc_features = bidmc_oscillation.fit_transform(
    bidmc
)

bidmc_objects = bidmc_oscillation.summarize(
    bidmc_features,
    signal="respiration",
)

In [27]:
eastman_objects

,fault_number,simulation_run,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,temporal_symmetry
0,1,1,1,True,32.0,34.0,35.0,2,1,3,NaN,0.000412,0.666667
1,1,1,2,True,35.0,37.0,40.0,2,3,5,3.0,0.000695,0.800000
2,1,1,3,True,40.0,51.0,74.0,11,23,34,14.0,0.004639,0.647059
3,1,1,4,True,74.0,75.0,76.0,1,1,2,24.0,0.000231,1.000000
4,1,1,5,True,76.0,87.0,91.0,11,4,15,12.0,0.001244,0.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,1,1,199,True,2929.0,2942.0,2950.0,13,8,21,14.0,0.002042,0.761905
199,1,1,200,True,2950.0,2954.0,2959.0,4,5,9,12.0,0.001465,0.888889
200,1,1,201,True,2959.0,2971.0,2977.0,12,6,18,17.0,0.001681,0.666667
201,1,1,202,True,2977.0,2979.0,2986.0,2,7,9,8.0,0.001069,0.444444
202,1,1,203,True,2986.0,2987.0,2991.0,1,4,5,8.0,0.000580,0.400000

In [25]:
eastman_accumulation = fg.accumulation.Accumulation(signals='reactor_temperature', group=["fault_number", "simulation_run"])
eastman_accumulation_features = eastman_accumulation.fit_transform(eastman_features)
eastman_accumulation_objects = eastman_accumulation.summarize(eastman_accumulation_features, signal='reactor_temperature')
eastman_accumulation_objects

,fault_number,simulation_run,accumulation_id,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,1,1,0,0,31,32,122.873796,0.837794,0.000000,0.837794,0.000000,0.026181,0.000000,15.398347,16
1,1,1,1,32,34,3,122.896609,0.015214,0.015214,0.012712,0.002502,0.005071,0.328880,0.328880,0
2,1,1,2,35,39,5,122.896695,0.022736,0.006108,0.003971,0.018766,0.004547,0.349288,2.899176,3
3,1,1,3,40,73,34,122.877444,0.708018,0.298830,0.298830,0.409188,0.020824,0.844130,15.448906,15
4,1,1,4,74,75,2,122.889032,0.013375,0.013375,0.013375,0.000000,0.006688,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1,1,200,2950,2958,9,122.886063,0.120266,0.066918,0.057916,0.062351,0.013363,0.963123,3.627825,4
201,1,1,201,2959,2976,18,122.876560,0.410987,0.319000,0.311594,0.099393,0.022833,0.483678,7.473886,7
202,1,1,202,2977,2985,9,122.892931,0.091317,0.032482,0.022282,0.069035,0.010146,0.488016,4.403274,5
203,1,1,203,2986,2990,5,122.887807,0.051022,0.018942,0.018942,0.032080,0.010204,0.742503,2.149827,3
204,1,1,204,2991,3000,10,122.882224,0.180813,0.000000,0.180813,0.000000,0.018081,0.000000,4.441151,4

In [26]:
bidmc_accumulation = fg.accumulation.Accumulation(signals='respiration', group='subject')
bidmc_accumulation_features = bidmc_accumulation.fit_transform(bidmc_features)
bidmc_accumulation_objects = bidmc_accumulation.summarize(bidmc_accumulation_features, signal='respiration')
bidmc_accumulation_objects

,subject,accumulation_id,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,1,0,0,9,10,0.353860,0.093840,0.000000,0.093840,0.000000,0.009384,0.000000,5.989344,6
1,1,1,10,79,70,0.018573,9.866038,1.737045,1.393938,8.472100,0.140943,0.282573,18.677637,15
2,1,2,80,290,211,0.030303,121.809414,45.742933,44.773236,77.036178,0.577296,0.735136,105.345667,103
3,1,3,291,364,74,0.019550,9.390079,2.138800,1.906150,7.483929,0.126893,0.405992,24.088458,21
4,1,4,365,551,187,0.037146,107.700804,49.525838,48.562984,59.137820,0.575940,0.901813,96.828786,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550,1,550,59525,59619,95,0.096774,11.942353,8.267878,8.030342,3.912011,0.125709,0.655149,32.519312,33
551,1,551,59620,59676,57,0.098729,3.753673,2.547406,2.442815,1.310858,0.065854,0.698440,33.322150,33
552,1,552,59677,59878,202,0.169110,98.348120,54.841690,54.010800,44.337320,0.486872,0.901640,107.061031,110
553,1,553,59879,59963,85,0.126100,11.359690,6.927640,6.677400,4.682290,0.133643,0.824369,26.060680,25
554,1,554,59964,60000,37,0.133920,1.027380,0.830900,0.790820,0.236560,0.027767,0.460511,19.904719,20