In [11]:
%load_ext autoreload
%autoreload 2

import featuregraph as fg

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [12]:
dataset = 'eastman'

In [13]:
eastman = fg.datasets.eastman(
    dataset="faultfree_training",
    fault_number=0,
    simulation_run=1,
)

# The fault-free workbook stores its 41 measurement channels under xmv_* labels.
# Its seventh channel is the Tennessee Eastman reactor-pressure measurement (XMEAS 7).
eastman = eastman.assign(
    reactor_pressure=eastman["separator_underflow_valve"]
)

group = ["fault_number", "simulation_run"]

eastman_oscillation = fg.oscillation.Oscillation(
    signals="reactor_pressure",
    group=group,
    smooth_signal=True,
    smooth_window=20,
)
eastman_oscillation_features = eastman_oscillation.fit_transform(eastman)
eastman_oscillation_objects = eastman_oscillation.summarize(
    eastman_oscillation_features,
    signal="reactor_pressure",
)

eastman_accumulation = fg.accumulation.Accumulation(
    signals="reactor_pressure",
    group=group,
)
eastman_accumulation_features = eastman_accumulation.fit_transform(
    eastman_oscillation_features
)
eastman_accumulation_objects = eastman_accumulation.summarize(
    eastman_accumulation_features,
    signal="reactor_pressure",
)

In [14]:
eastman_oscillation_objects.table

,fault_number,simulation_run,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry
0,0,1,1,True,28.0,42.0,65.0,14.0,23.0,37.0,NaN,0.602793,0.086113,0.052417,0.077322,0.094659,0.756757
1,0,1,2,True,65.0,79.0,82.0,14.0,3.0,17.0,37.0,0.164034,0.023433,0.109356,0.044501,0.002363,0.352941
2,0,1,3,True,82.0,85.0,113.0,3.0,28.0,31.0,6.0,0.339154,0.226103,0.024225,0.006543,0.046929,0.193548
3,0,1,4,True,113.0,116.0,121.0,3.0,5.0,8.0,31.0,0.058529,0.039019,0.023412,0.005000,0.007974,0.750000
4,0,1,5,True,121.0,136.0,153.0,15.0,17.0,32.0,20.0,0.348853,0.046514,0.041041,0.052446,0.055447,0.937500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,0,1,60,True,2820.0,2850.0,2851.0,30.0,1.0,31.0,65.0,0.700537,0.046702,1.401074,0.081941,0.000337,0.064516
60,0,1,61,True,2851.0,2865.0,2902.0,14.0,37.0,51.0,15.0,0.772746,0.110392,0.041770,0.020752,0.069514,0.549020
61,0,1,62,True,2902.0,2910.0,2912.0,8.0,2.0,10.0,45.0,0.104112,0.026028,0.104112,0.026082,0.002227,0.400000
62,0,1,63,True,2912.0,2913.0,2916.0,1.0,3.0,4.0,3.0,0.020116,0.040232,0.013411,0.001333,0.008255,0.500000
63,0,1,64,True,2916.0,2956.0,2984.0,40.0,28.0,68.0,43.0,1.460540,0.073027,0.104324,0.128338,0.153730,0.823529

In [15]:
eastman_accumulation_objects.table

,fault_number,simulation_run,accumulation_id,is_complete,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,0,1,1,True,29,65,37,2798.673776,55.514964,29.381302,27.695562,27.819402,1.500404,0.997769,14.736988,13
1,0,1,2,True,66,82,17,2799.279371,14.567480,12.367642,12.135012,2.432468,0.856911,0.333959,6.713977,6
2,0,1,3,True,83,113,31,2798.618562,30.365655,4.878242,3.867265,26.498390,0.979537,0.254713,14.295664,14
3,0,1,4,True,114,121,8,2799.245245,2.531252,1.104793,0.626832,1.904420,0.316406,0.495274,4.087393,5
4,0,1,5,True,122,153,32,2798.095361,54.767058,29.407314,29.329159,25.437899,1.711471,0.928949,14.278402,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,0,1,60,True,2821,2851,31,2798.430105,57.174933,55.123707,52.690565,4.484368,1.844353,0.156865,15.631573,16
60,0,1,61,True,2852,2902,51,2798.311330,67.700441,28.325232,27.602648,40.097793,1.327460,0.815435,19.550961,17
61,0,1,62,True,2903,2912,10,2798.227619,7.631621,4.900494,4.115589,3.516032,0.763162,0.921438,4.754369,4
62,0,1,63,True,2913,2916,4,2799.239652,1.398760,0.507351,0.000000,1.398760,0.349690,0.000000,1.728558,2
63,0,1,64,True,2917,2984,68,2798.449369,145.889105,116.373671,113.744677,32.144428,2.145428,0.440669,28.626970,27

In [16]:
faulty_eastman = fg.datasets.eastman(
    dataset="faulty_training",
    fault_number=1,
    simulation_run=1,
)

faulty_group = ["fault_number", "simulation_run"]

faulty_eastman_oscillation = fg.oscillation.Oscillation(
    signals="reactor_pressure",
    group=faulty_group,
    smooth_signal=True,
    smooth_window=20,
)
faulty_eastman_oscillation_features = faulty_eastman_oscillation.fit_transform(
    faulty_eastman
)
faulty_eastman_oscillation_objects = faulty_eastman_oscillation.summarize(
    faulty_eastman_oscillation_features,
    signal="reactor_pressure",
)

faulty_eastman_accumulation = fg.accumulation.Accumulation(
    signals="reactor_pressure",
    group=faulty_group,
)
faulty_eastman_accumulation_features = faulty_eastman_accumulation.fit_transform(
    faulty_eastman_oscillation_features
)
faulty_eastman_accumulation_objects = faulty_eastman_accumulation.summarize(
    faulty_eastman_accumulation_features,
    signal="reactor_pressure",
)

In [17]:
faulty_eastman_oscillation_objects.table

,fault_number,simulation_run,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry
0,1,1,1,True,28.0,30.0,42.0,2.0,12.0,14.0,NaN,0.132400,0.132400,0.022067,0.019628,0.028350,0.285714
1,1,1,2,True,42.0,43.0,44.0,1.0,1.0,2.0,13.0,0.015504,0.031008,0.031008,0.001295,0.000686,1.000000
2,1,1,3,True,44.0,75.0,104.0,31.0,29.0,60.0,32.0,1.397994,0.090193,0.096413,0.088062,0.144047,0.966667
3,1,1,4,True,104.0,115.0,116.0,11.0,1.0,12.0,40.0,0.063443,0.011535,0.126886,0.018340,0.003315,0.166667
4,1,1,5,True,116.0,147.0,164.0,31.0,17.0,48.0,32.0,0.551637,0.035589,0.064898,0.072668,0.070951,0.708333
5,1,1,6,True,164.0,204.0,207.0,40.0,3.0,43.0,57.0,0.406232,0.020312,0.270821,0.031786,0.013114,0.139535
6,1,1,7,True,207.0,234.0,275.0,27.0,41.0,68.0,30.0,1.060868,0.078583,0.051750,0.049425,0.086173,0.794118
7,1,1,8,True,275.0,305.0,346.0,30.0,41.0,71.0,71.0,1.332329,0.088822,0.064992,0.121052,0.114744,0.845070
8,1,1,9,True,346.0,381.0,420.0,35.0,39.0,74.0,76.0,1.085307,0.062018,0.055657,0.108265,0.062131,0.945946
9,1,1,10,True,420.0,428.0,448.0,8.0,20.0,28.0,47.0,0.510682,0.127670,0.051068,0.023021,0.074100,0.571429
10,1,1,11,True,448.0,469.0,491.0,21.0,22.0,43.0,41.0,0.371507,0.035382,0.033773,0.066299,0.043331,0.976744
11,1,1,12,True,491.0,494.0,498.0,3.0,4.0,7.0,25.0,0.135117,0.090078,0.067559,0.004090,0.005926,0.857143
12,1,1,13,True,498.0,535.0,577.0,37.0,42.0,79.0,41.0,1.069514,0.057812,0.050929,0.096751,0.060451,0.936709
13,1,1,14,True,577.0,586.0,609.0,9.0,23.0,32.0,51.0,0.274522,0.061005,0.023871,0.024530,0.032804,0.562500
14,1,1,15,True,609.0,658.0,794.0,49.0,136.0,185.0,72.0,11.860252,0.484092,0.174415,0.452913,0.351391,0.529730
15,1,1,16,True,794.0,825.0,923.0,31.0,98.0,129.0,167.0,14.356878,0.926250,0.292998,0.088628,0.444162,0.480620
16,1,1,17,True,923.0,1053.0,1122.0,130.0,69.0,199.0,228.0,23.782994,0.365892,0.689362,0.643642,0.300977,0.693467
17,1,1,18,True,1122.0,1205.0,1287.0,83.0,82.0,165.0,152.0,2.319355,0.055888,0.056570,0.095509,0.101693,0.993939
18,1,1,19,True,1287.0,1316.0,1347.0,29.0,31.0,60.0,111.0,0.990875,0.068336,0.063927,0.109799,0.091300,0.966667
19,1,1,20,True,1347.0,1352.0,1384.0,5.0,32.0,37.0,36.0,0.766325,0.306530,0.047895,0.018092,0.093384,0.270270
20,1,1,21,True,1384.0,1409.0,1430.0,25.0,21.0,46.0,57.0,0.706629,0.056530,0.067298,0.089598,0.067239,0.913043
21,1,1,22,True,1430.0,1452.0,1461.0,22.0,9.0,31.0,43.0,0.507472,0.046134,0.112772,0.092084,0.020300,0.580645
22,1,1,23,True,1461.0,1510.0,1549.0,49.0,39.0,88.0,58.0,1.489048,0.060777,0.076361,0.084434,0.144973,0.886364
23,1,1,24,True,1549.0,1587.0,1598.0,38.0,11.0,49.0,77.0,1.262442,0.066444,0.229535,0.123782,0.029734,0.448980
24,1,1,25,True,1598.0,1603.0,1614.0,5.0,11.0,16.0,16.0,0.154558,0.061823,0.028101,0.013741,0.029366,0.625000
25,1,1,26,True,1614.0,1638.0,1659.0,24.0,21.0,45.0,35.0,0.653126,0.054427,0.062202,0.108756,0.072502,0.933333
26,1,1,27,True,1659.0,1679.0,1708.0,20.0,29.0,49.0,41.0,0.952367,0.095237,0.065681,0.029908,0.096846,0.816327
27,1,1,28,True,1708.0,1732.0,1764.0,24.0,32.0,56.0,53.0,0.890048,0.074171,0.055628,0.071367,0.098079,0.857143
28,1,1,29,True,1764.0,1817.0,1842.0,53.0,25.0,78.0,85.0,1.313833,0.049579,0.105107,0.082691,0.150865,0.641026
29,1,1,30,True,1842.0,1868.0,1872.0,26.0,4.0,30.0,51.0,0.329886,0.025376,0.164943,0.054387,0.009831,0.266667
30,1,1,31,True,1872.0,1875.0,1879.0,3.0,4.0,7.0,7.0,0.037297,0.024865,0.018649,0.004789,0.009808,0.857143
31,1,1,32,True,1879.0,1901.0,1920.0,22.0,19.0,41.0,26.0,0.412278,0.037480,0.043398,0.061275,0.054413,0.926829
32,1,1,33,True,1920.0,1931.0,1955.0,11.0,24.0,35.0,30.0,0.736700,0.133945,0.061392,0.026687,0.088989,0.628571
33,1,1,34,True,1955.0,1976.0,2005.0,21.0,29.0,50.0,45.0,0.663309,0.063172,0.045745,0.089235,0.071078,0.840000
34,1,1,35,True,2005.0,2047.0,2048.0,42.0,1.0,43.0,71.0,1.227782,0.058466,2.455563,0.124838,0.003618,0.046512
35,1,1,36,True,2048.0,2052.0,2099.0,4.0,47.0,51.0,5.0,1.316973,0.658487,0.056041,0.007405,0.108536,0.156863
36,1,1,37,True,2099.0,2122.0,2148.0,23.0,26.0,49.0,70.0,0.668473,0.058128,0.051421,0.083943,0.079588,0.938776
37,1,1,38,True,2148.0,2174.0,2195.0,26.0,21.0,47.0,52.0,0.783883,0.060299,0.074656,0.099350,0.070362,0.893617
38,1,1,39,True,2195.0,2221.0,2245.0,26.0,24.0,50.0,47.0,0.470284,0.036176,0.039190,0.071969,0.053274,0.960000
39,1,1,40,True,2245.0,2273.0,2295.0,28.0,22.0,50.0,52.0,0.453980,0.032427,0.041271,0.028757,0.054363,0.880000
40,1,1,41,True,2295.0,2300.0,2326.0,5.0,26.0,31.0,27.0,0.639598,0.255839,0.049200,0.012816,0.072913,0.322581
41,1,1,42,True,2326.0,2362.0,2385.0,36.0,23.0,59.0,62.0,0.890591,0.049477,0.077443,0.099898,0.074852,0.779661
42,1,1,43,True,2385.0,2435.0,2501.0,50.0,66.0,116.0,73.0,2.234683,0.089387,0.067718,0.111347,0.142790,0.862069
43,1,1,44,True,2501.0,2528.0,2544.0,27.0,16.0,43.0,93.0,0.567099,0.042007,0.070887,0.081220,0.037949,0.744186
44,1,1,45,True,2544.0,2563.0,2564.0,19.0,1.0,20.0,35.0,0.202176,0.021282,0.404353,0.039179,0.004152,0.100000
45,1,1,46,True,2564.0,2607.0,2632.0,43.0,25.0,68.0,44.0,0.854142,0.039728,0.068331,0.078269,0.089870,0.735294
46,1,1,47,True,2632.0,2650.0,2673.0,18.0,23.0,41.0,43.0,1.058520,0.117613,0.092045,0.082224,0.137787,0.878049
47,1,1,48,True,2673.0,2692.0,2703.0,19.0,11.0,30.0,42.0,0.413217,0.043496,0.075130,0.089852,0.031807,0.733333
48,1,1,49,True,2703.0,2736.0,2743.0,33.0,7.0,40.0,44.0,0.358539,0.021730,0.102440,0.045086,0.012311,0.350000
49,1,1,50,True,2743.0,2745.0,2781.0,2.0,36.0,38.0,9.0,0.836181,0.836181,0.046454,0.004280,0.080381,0.105263
50,1,1,51,True,2781.0,2815.0,2845.0,34.0,30.0,64.0,70.0,1.423312,0.083724,0.094887,0.152962,0.085858,0.937500
51,1,1,52,True,2845.0,2860.0,2861.0,15.0,1.0,16.0,45.0,0.154261,0.020568,0.308522,0.028333,0.005953,0.125000
52,1,1,53,True,2861.0,2862.0,2884.0,1.0,22.0,23.0,2.0,0.690043,1.380086,0.062731,0.000278,0.104510,0.086957
53,1,1,54,True,2884.0,2910.0,2922.0,26.0,12.0,38.0,48.0,0.950584,0.073122,0.158431,0.164052,0.050894,0.631579
54,1,1,55,True,2922.0,2925.0,2963.0,3.0,38.0,41.0,15.0,0.486503,0.324336,0.025605,0.004262,0.044116,0.146341
55,1,1,56,True,2963.0,2971.0,2974.0,8.0,3.0,11.0,46.0,0.055311,0.013828,0.036874,0.014742,0.004207,0.545455

In [18]:
faulty_eastman_accumulation_objects.table

,fault_number,simulation_run,accumulation_id,is_complete,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,1,1,1,True,29,42,14,2799.194092,12.808916,0.599744,0.000000,12.808916,0.914923,0.000000,8.839153,10
1,1,1,2,True,43,44,2,2799.744236,1.105305,1.105305,0.000000,1.105305,0.552652,0.000000,0.000000,0
2,1,1,3,True,45,104,60,2798.134455,126.409572,99.969092,97.924688,28.484883,2.106826,0.450676,21.538579,19
3,1,1,4,True,105,116,12,2798.544512,7.511703,7.153884,6.662116,0.849588,0.625975,0.226204,4.513539,4
4,1,1,5,True,117,164,48,2798.310829,72.349486,51.000620,50.421190,21.928296,1.507281,0.606177,23.168093,20
5,1,1,6,True,165,207,43,2799.049821,49.112208,46.062410,43.997280,5.114929,1.142144,0.208296,22.890369,23
6,1,1,7,True,208,275,68,2798.275534,118.213022,70.279811,68.454942,49.758080,1.738427,0.841838,24.690255,22
7,1,1,8,True,276,346,71,2797.815417,154.502292,97.361359,94.406116,60.096176,2.176089,0.777932,25.807050,23
8,1,1,9,True,347,420,74,2798.565390,126.852664,74.043332,72.486414,54.366250,1.714225,0.857156,32.326067,30
9,1,1,10,True,421,448,28,2797.805100,35.998311,12.819007,11.179272,24.819039,1.285654,0.621100,14.335101,15
10,1,1,11,True,449,491,43,2798.016993,60.272521,33.463249,32.118270,28.154251,1.401687,0.934232,19.652307,18
11,1,1,12,True,492,498,7,2798.835953,4.773782,1.948096,1.724366,3.049415,0.681969,0.722432,3.032846,4
12,1,1,13,True,499,577,79,2798.824840,136.546564,81.844603,80.113812,56.432752,1.728438,0.826572,33.645855,30
13,1,1,14,True,578,609,32,2798.614323,33.310206,11.048494,10.681865,22.628341,1.040944,0.641357,14.062976,14
14,1,1,15,True,610,794,185,2786.070983,2433.473838,1095.626027,1070.350524,1363.123314,13.153913,0.879689,59.333439,54
15,1,1,16,True,795,923,129,2759.328409,1933.202610,898.519746,870.544422,1062.658188,14.986067,0.900624,36.922446,33
16,1,1,17,True,924,1122,199,2761.025415,6409.024798,3727.123106,3680.659840,2728.364958,32.206155,0.851413,118.047680,118
17,1,1,18,True,1123,1287,165,2797.621938,430.159866,248.091196,242.927364,187.232502,2.607029,0.870525,77.585579,75
18,1,1,19,True,1288,1347,60,2798.078538,97.421125,65.230456,64.036646,33.384479,1.623685,0.685364,23.719910,21
19,1,1,20,True,1348,1384,37,2796.208406,65.662054,10.543387,8.937637,56.724418,1.774650,0.272231,17.265574,15
20,1,1,21,True,1385,1430,46,2797.126352,70.124473,49.518533,48.614584,21.509889,1.524445,0.613477,19.452847,16
21,1,1,22,True,1431,1461,31,2797.872985,43.963460,29.236198,27.820167,16.143293,1.418176,0.734396,14.781030,13
22,1,1,23,True,1462,1549,88,2797.279381,220.671395,157.689471,154.190286,66.481108,2.507629,0.602535,36.610210,35
23,1,1,24,True,1550,1598,49,2798.199608,107.384848,80.815247,78.666775,28.718073,2.191528,0.534863,27.540566,27
24,1,1,25,True,1599,1614,16,2799.352920,17.731215,5.317802,4.517793,13.213422,1.108201,0.509586,8.637107,9
25,1,1,26,True,1615,1659,45,2799.565924,78.783012,50.413765,49.078824,29.704188,1.750734,0.754076,19.292733,16
26,1,1,27,True,1660,1708,49,2797.568280,129.563250,71.327993,67.845704,61.717546,2.644148,0.952701,20.340083,18
27,1,1,28,True,1709,1764,56,2797.428600,117.365289,68.019676,65.726295,51.638994,2.095809,0.879970,22.733800,20
28,1,1,29,True,1765,1842,78,2798.095932,163.951518,139.451390,137.497156,26.454362,2.101943,0.322710,34.274896,34
29,1,1,30,True,1843,1872,30,2798.760298,26.645554,24.908694,24.770090,1.875464,0.888185,0.140771,13.903418,14
30,1,1,31,True,1873,1879,7,2799.367889,5.160881,1.744038,0.972369,4.188512,0.737269,0.376823,3.441770,3
31,1,1,32,True,1880,1920,41,2799.358691,37.013362,24.740804,24.736033,12.277329,0.902765,0.663400,16.806037,13
32,1,1,33,True,1921,1955,35,2797.916501,51.018659,24.490573,23.231925,27.786735,1.457676,0.910723,15.559673,13
33,1,1,34,True,1956,2005,50,2797.518574,97.108872,54.320697,52.176271,44.932600,1.942177,0.925407,21.000259,18
34,1,1,35,True,2006,2048,43,2799.699631,64.295527,63.545404,63.436070,0.859457,1.495245,0.026735,22.650738,24
35,1,1,36,True,2049,2099,51,2798.187851,73.209310,12.438996,9.718564,63.490746,1.435477,0.265501,17.036270,13
36,1,1,37,True,2100,2148,49,2797.879758,87.292684,52.918068,50.456456,36.836227,1.781483,0.843971,20.010606,17
37,1,1,38,True,2149,2195,47,2798.651533,75.407999,48.929645,48.156140,27.251859,1.604426,0.722784,20.743656,18
38,1,1,39,True,2196,2245,50,2798.689764,91.171060,54.880218,53.863516,37.307544,1.823421,0.818408,22.388230,21
39,1,1,40,True,2246,2295,50,2798.732497,79.899537,52.939675,51.268137,28.631400,1.597991,0.716685,22.121877,20
40,1,1,41,True,2296,2326,31,2798.000731,29.877583,7.348025,6.496904,23.380679,0.963793,0.434902,13.972385,13
41,1,1,42,True,2327,2385,59,2798.304587,98.102183,70.327679,68.123002,29.979181,1.662749,0.611183,27.883723,26
42,1,1,43,True,2386,2501,116,2797.414693,334.509496,217.626918,213.633011,120.876485,2.883703,0.722709,42.833803,39
43,1,1,44,True,2502,2544,43,2797.353586,81.438772,50.895874,49.067263,32.371508,1.893925,0.794990,21.073595,20
44,1,1,45,True,2545,2564,20,2798.308129,21.009839,19.744797,18.503987,2.505852,1.050492,0.238541,10.119837,9
45,1,1,46,True,2565,2632,68,2798.734644,125.448561,88.801313,87.207921,38.240640,1.844832,0.609662,32.235449,31
46,1,1,47,True,2633,2673,41,2797.600720,87.397925,54.037321,52.597005,34.800920,2.131657,0.796379,16.920655,13
47,1,1,48,True,2674,2703,30,2798.766037,32.805758,18.993770,18.051829,14.753929,1.093525,0.899472,14.258168,14
48,1,1,49,True,2704,2743,40,2799.165390,49.570768,38.370807,36.996922,12.573846,1.239269,0.507309,21.066316,21
49,1,1,50,True,2744,2781,38,2798.111425,38.187460,4.445290,2.373019,35.814441,1.004933,0.124283,16.147681,14
50,1,1,51,True,2782,2845,64,2798.803675,115.974051,79.841101,77.015045,38.959007,1.812095,0.671857,27.602745,24
51,1,1,52,True,2846,2861,16,2798.678339,22.549757,21.144748,20.457285,2.092472,1.409360,0.185587,7.533806,9
52,1,1,53,True,2862,2884,23,2796.930491,41.890112,2.731937,0.000000,41.890112,1.821309,0.000000,13.438591,15
53,1,1,54,True,2885,2922,38,2799.381210,48.655955,35.424255,34.897318,13.758637,1.280420,0.565548,16.749656,15
54,1,1,55,True,2923,2963,41,2798.755464,41.297711,4.648345,2.699888,38.597823,1.007261,0.130752,18.544622,18
55,1,1,56,True,2964,2974,11,2798.941510,6.992437,5.648276,5.564602,1.427835,0.635676,0.408394,4.483347,4