In [1]:
%load_ext autoreload
%autoreload 2

import sys
import featuregraph as fg

print("Python:", sys.executable)
print("FeatureGraph:", fg.__file__)

Python: /usr/local/bin/python
FeatureGraph: /workspaces/featuregraph/src/featuregraph/__init__.py

In [ ]:
dataset = 'eastman'

In [2]:
eastman = fg.datasets.eastman(fault_number=1, simulation_run=1)

eastman_oscillation = fg.oscillation.Oscillation(signals="reactor_temperature", group=["fault_number", "simulation_run"], smooth_signal=True, smooth_window=20)
eastman_oscillation_features = eastman_oscillation.fit_transform(eastman)
eastman_oscillation_objects = eastman_oscillation.summarize(eastman_oscillation_features, signal="reactor_temperature",)

eastman_accumulation = fg.accumulation.Accumulation(signals='reactor_temperature', group=["fault_number", "simulation_run"])
eastman_accumulation_features = eastman_accumulation.fit_transform(eastman_oscillation_features)
eastman_accumulation_objects = eastman_accumulation.summarize(eastman_accumulation_features, signal='reactor_temperature')

In [4]:
eastman_oscillation_objects

,fault_number,simulation_run,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry
0,1,1,1,True,32.0,34.0,35.0,2,1,3,NaN,0.000412,0.000412,0.000824,0.000153,0.000012,0.666667
1,1,1,2,True,35.0,37.0,40.0,2,3,5,3.0,0.000695,0.000695,0.000463,0.000131,0.000037,0.800000
2,1,1,3,True,40.0,51.0,74.0,11,23,34,14.0,0.004639,0.000843,0.000403,0.000343,0.000602,0.647059
3,1,1,4,True,74.0,75.0,76.0,1,1,2,24.0,0.000231,0.000462,0.000462,0.000037,0.000002,1.000000
4,1,1,5,True,76.0,87.0,91.0,11,4,15,12.0,0.001244,0.000226,0.000622,0.000485,0.000097,0.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,1,1,199,True,2929.0,2942.0,2950.0,13,8,21,14.0,0.002042,0.000314,0.000510,0.000342,0.000256,0.761905
199,1,1,200,True,2950.0,2954.0,2959.0,4,5,9,12.0,0.001465,0.000733,0.000586,0.000170,0.000258,0.888889
200,1,1,201,True,2959.0,2971.0,2977.0,12,6,18,17.0,0.001681,0.000280,0.000560,0.000496,0.000336,0.666667
201,1,1,202,True,2977.0,2979.0,2986.0,2,7,9,8.0,0.001069,0.001069,0.000305,0.000046,0.000192,0.444444
202,1,1,203,True,2986.0,2987.0,2991.0,1,4,5,8.0,0.000580,0.001160,0.000290,0.000009,0.000066,0.400000

In [5]:
eastman_accumulation_objects

,fault_number,simulation_run,accumulation_id,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,1,1,0,0,31,32,122.873796,0.837794,0.000000,0.837794,0.000000,0.026181,0.000000,15.398347,16
1,1,1,1,32,34,3,122.896609,0.015214,0.015214,0.012712,0.002502,0.005071,0.328880,0.328880,0
2,1,1,2,35,39,5,122.896695,0.022736,0.006108,0.003971,0.018766,0.004547,0.349288,2.899176,3
3,1,1,3,40,73,34,122.877444,0.708018,0.298830,0.298830,0.409188,0.020824,0.844130,15.448906,15
4,1,1,4,74,75,2,122.889032,0.013375,0.013375,0.013375,0.000000,0.006688,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1,1,200,2950,2958,9,122.886063,0.120266,0.066918,0.057916,0.062351,0.013363,0.963123,3.627825,4
201,1,1,201,2959,2976,18,122.876560,0.410987,0.319000,0.311594,0.099393,0.022833,0.483678,7.473886,7
202,1,1,202,2977,2985,9,122.892931,0.091317,0.032482,0.022282,0.069035,0.010146,0.488016,4.403274,5
203,1,1,203,2986,2990,5,122.887807,0.051022,0.018942,0.018942,0.032080,0.010204,0.742503,2.149827,3
204,1,1,204,2991,3000,10,122.882224,0.180813,0.000000,0.180813,0.000000,0.018081,0.000000,4.441151,4