In [5]:
%load_ext autoreload
%autoreload 2

import sys
import featuregraph as fg

print("Python:", sys.executable)
print("FeatureGraph:", fg.__file__)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Python: /workspaces/featuregraph/.venv/bin/python
FeatureGraph: /workspaces/featuregraph/src/featuregraph/__init__.py

In [6]:
bidmc = fg.datasets.bidmc(subject=1)

bidmc_oscillation = fg.oscillation.Oscillation(signals="respiration", group="subject", smooth_signal=False)
bidmc_oscillation_features = bidmc_oscillation.fit_transform(bidmc)
bidmc_oscillation_objects = bidmc_oscillation.summarize(bidmc_oscillation_features, signal="respiration")

bidmc_accumulation = fg.accumulation.Accumulation(signals='respiration', group='subject')
bidmc_accumulation_features = bidmc_accumulation.fit_transform(bidmc_oscillation_features)
bidmc_accumulation_objects = bidmc_accumulation.summarize(bidmc_accumulation_features, signal='respiration')

In [7]:
bidmc_oscillation_objects.table

,subject,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry
0,1,1,True,9.0,13.0,79.0,4.0,66.0,70.0,NaN,0.174974,0.087487,0.005302,0.001466,0.011535,0.114286
1,1,2,True,79.0,166.0,290.0,87.0,124.0,211.0,153.0,0.484849,0.011146,0.007820,0.015445,0.019452,0.824645
2,1,3,True,290.0,298.0,364.0,8.0,66.0,74.0,132.0,0.120235,0.030059,0.003643,0.000880,0.007038,0.216216
3,1,4,True,364.0,456.0,551.0,92.0,95.0,187.0,158.0,0.481427,0.010466,0.010135,0.013490,0.026002,0.983957
4,1,5,True,551.0,576.0,641.0,25.0,65.0,90.0,120.0,0.184262,0.014741,0.005670,0.004496,0.010753,0.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,1,549,True,59443.0,59458.0,59524.0,15.0,66.0,81.0,46.0,0.389050,0.051873,0.011789,0.001760,0.019844,0.370370
549,1,550,True,59524.0,59566.0,59619.0,42.0,53.0,95.0,108.0,0.122188,0.005818,0.004611,0.004887,0.009873,0.884211
550,1,551,True,59619.0,59658.0,59676.0,39.0,18.0,57.0,92.0,0.058160,0.002983,0.006462,0.004985,0.004496,0.631579
551,1,552,True,59676.0,59792.0,59878.0,116.0,86.0,202.0,134.0,0.415445,0.007163,0.009662,0.011535,0.029227,0.851485
552,1,553,True,59878.0,59907.0,59963.0,29.0,56.0,85.0,115.0,0.131475,0.009067,0.004696,0.004399,0.009482,0.682353

In [8]:
bidmc_accumulation_objects.table

,subject,accumulation_id,is_complete,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,1,1,True,10,79,70,0.018573,9.866038,1.393938,1.046921,8.819117,0.140943,0.212227,18.677637,15
1,1,2,True,80,290,211,0.030303,121.809414,44.773236,43.803539,78.005875,0.577296,0.719214,105.345667,103
2,1,3,True,291,364,74,0.019550,9.390079,1.906150,1.671550,7.718529,0.126893,0.356025,24.088458,21
3,1,4,True,365,551,187,0.037146,107.700804,48.562984,47.600130,60.100674,0.575940,0.883933,96.828786,97
4,1,5,True,552,641,90,0.001955,17.829916,8.507335,8.146630,9.683286,0.198110,0.913816,28.455305,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,1,549,True,59444,59524,81,0.221900,35.584210,11.637290,10.859190,24.725020,0.439311,0.610338,24.223738,22
549,1,550,True,59525,59619,95,0.096774,11.942353,8.030342,7.790846,4.151507,0.125709,0.695258,32.519312,33
550,1,551,True,59620,59676,57,0.098729,3.753673,2.442815,2.336264,1.417409,0.065854,0.755212,33.322150,33
551,1,552,True,59677,59878,202,0.169110,98.348120,54.010800,53.179910,45.168210,0.486872,0.918537,107.061031,110
552,1,553,True,59879,59963,85,0.126100,11.359690,6.677400,6.422270,4.937420,0.133643,0.869288,26.060680,25

In [13]:
tep = fg.datasets.eastman(fault_number=2, simulation_run=1,)

tep_oscillation = fg.oscillation.Oscillation(signals='reactor_pressure', group=['fault_number', 'simulation_run'], smooth_signal=True)
tep_oscillation_features = tep_oscillation.fit_transform(tep)
tep_oscillation_objects = tep_oscillation.summarize(tep_oscillation_features, signal="reactor_pressure")

tep_accumulation = fg.accumulation.Accumulation(signals='reactor_pressure', group=['fault_number', 'simulation_run'])
tep_accumulation_features = tep_accumulation.fit_transform(tep_oscillation_features)
tep_accumulation_objects = tep_accumulation.summarize(tep_accumulation_features, signal='reactor_pressure')

In [14]:
tep_oscillation_objects.table

,fault_number,simulation_run,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,amplitude,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry
0,2,1,1,True,28.0,31.0,42.0,3.0,11.0,14.0,NaN,0.122800,0.081867,0.022327,0.024867,0.026885,0.428571
1,2,1,2,True,42.0,68.0,125.0,26.0,57.0,83.0,37.0,1.292808,0.099447,0.045362,0.101409,0.080290,0.626506
2,2,1,3,True,125.0,157.0,206.0,32.0,49.0,81.0,89.0,0.928933,0.058058,0.037916,0.074132,0.061699,0.790123
3,2,1,4,True,206.0,237.0,259.0,31.0,22.0,53.0,80.0,0.704034,0.045422,0.064003,0.091562,0.045042,0.830189
4,2,1,5,True,259.0,283.0,314.0,24.0,31.0,55.0,46.0,0.952518,0.079376,0.061453,0.072563,0.119418,0.872727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2,1,57,True,2758.0,2784.0,2810.0,26.0,26.0,52.0,27.0,0.637729,0.049056,0.049056,0.069896,0.079484,1.000000
57,2,1,58,True,2810.0,2837.0,2866.0,27.0,29.0,56.0,53.0,0.768244,0.056907,0.052982,0.086760,0.093279,0.964286
58,2,1,59,True,2866.0,2884.0,2912.0,18.0,28.0,46.0,47.0,0.518262,0.057585,0.037019,0.058408,0.056972,0.782609
59,2,1,60,True,2912.0,2925.0,2928.0,13.0,3.0,16.0,41.0,0.130132,0.020020,0.086755,0.035427,0.010005,0.375000
60,2,1,61,True,2928.0,2971.0,2992.0,43.0,21.0,64.0,46.0,0.587938,0.027346,0.055994,0.069403,0.077500,0.656250

In [15]:
tep_accumulation_objects.table

,fault_number,simulation_run,accumulation_id,is_complete,start_index,end_index,duration,baseline,total_auc,auc_at_peak,accumulation_before_peak,accumulation_from_peak,accumulation_rate,accumulation_symmetry,centroid_time,half_accumulation_time
0,2,1,1,True,29,42,14,2799.018661,15.151647,1.161115,0.799051,14.352596,1.082260,0.105474,8.908262,9
1,2,1,2,True,43,125,83,2798.186011,170.728781,86.309884,83.456194,87.272586,2.056973,0.977646,30.005816,25
2,2,1,3,True,126,206,81,2798.107660,136.535352,76.223696,75.217386,61.317966,1.685622,0.898199,31.732352,27
3,2,1,4,True,207,259,53,2798.319954,90.341096,61.290019,59.559640,30.781456,1.704549,0.681450,24.530252,23
4,2,1,5,True,260,314,55,2797.432780,140.022657,79.537535,77.551455,62.471203,2.545866,0.892301,23.354022,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2,1,57,True,2759,2810,52,2798.506838,88.141210,56.811717,55.527220,32.613990,1.695023,0.740040,22.095135,19
57,2,1,58,True,2811,2866,56,2798.682216,95.539517,61.578684,60.525317,35.014200,1.706063,0.732978,22.789085,20
58,2,1,59,True,2867,2912,46,2798.348391,59.251654,31.542917,30.579158,28.672497,1.288079,0.967821,18.976955,16
59,2,1,60,True,2913,2928,16,2798.507872,15.110105,12.083302,11.644556,3.465548,0.944382,0.458706,6.633231,7
60,2,1,61,True,2929,2992,64,2797.613811,161.064198,114.842256,111.575125,49.489073,2.516628,0.614526,30.997124,29

In [1]:
import featuregraph as fg

signals = fg.datasets.capnobase(case="0009")
labels = fg.datasets.capnobase_labels(case="0009")

AttributeError: module 'featuregraph.datasets' has no attribute 'capnobase'